server:
  port: 19093

spring:
  application:
    name: store-service
  datasource:
    url: jdbc:mysql://localhost:3306/userdb
    username: root
    password: Jesuslove1!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true # sql 로깅
        format_sql: true # SQL 문 정렬하여 출력
        highlight_sql: true # SQL 문 색 부여
  #        use_sql_comments: true # 콘솔에 표시되는 쿼리문 위에 어떤 실행을 하려는지 HINT 표시
  data:
    redis:
      host: 3.37.198.42
      port: 6379
      username: default
      password: systempass


eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/


naver:
  client-id:
  client-secret: 